config/routes.rb
Railsflisol::Application.routes.draw do
  resources :certificados

  get "certificados/new"
  get "certificados/show"
  resources :certificado

  root 'certificados#index'

end

app/models/certificado.rb
class Certificado < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/certificados_controller.rb
class CertificadosController < ApplicationController
  before_action :set_certificado, only: [:show, :edit, :update, :destroy]

  # GET /certificados
  # GET /certificados.json
  def index
    @certificados = Certificado.all
  end

  # GET /certificados/1
  # GET /certificados/1.json
  def show
  end

  # GET /certificados/new
  def new
    @certificado = Certificado.new
  end

  # GET /certificados/1/edit
  def edit
  end

  # POST /certificados
  # POST /certificados.json
  def create
    @certificado = Certificado.new(certificado_params)

    respond_to do |format|
      if @certificado.save
        format.html { redirect_to @certificado, notice: 'Certificado was successfully created.' }
        format.json { render action: 'show', status: :created, location: @certificado }
      else
        format.html { render action: 'new' }
        format.json { render json: @certificado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificados/1
  # PATCH/PUT /certificados/1.json
  def update
    respond_to do |format|
      if @certificado.update(certificado_params)
        format.html { redirect_to @certificado, notice: 'Certificado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @certificado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificados/1
  # DELETE /certificados/1.json
  def destroy
    @certificado.destroy
    respond_to do |format|
      format.html { redirect_to certificados_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificado
      @certificado = Certificado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificado_params
      params.require(:certificado).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/certificados_helper.rb
module CertificadosHelper
end

app/views/certificados/_form.html.erb
<%= simple_form_for(@certificado) do |f| %>
  <% if @certificado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certificado.errors.count, "error") %> prohibited this certificado from being saved:</h2>

      <ul>
      <% @certificado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.text_field :nombre %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certificados/edit.html.erb
<h1>Editing certificado</h1>

<%= render 'form' %>

<%= link_to 'Show', @certificado %> |
<%= link_to 'Back', certificados_path %>

app/views/certificados/index.html.erb
<h1>Listing certificados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @certificados.each do |certificado| %>
      <tr>
        <td><%= certificado.nombre %></td>
        <td><%= link_to 'Show', certificado_path(certificado.id, :format => "pdf") %></td>
        <td><%= link_to 'Edit', edit_certificado_path(certificado) %></td>
        <td><%= link_to 'Destroy', certificado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Certificado', new_certificado_path %>

app/views/certificados/new.html.erb
<h1>New certificado</h1>

<%= render 'form' %>

<%= link_to 'Back', certificados_path %>

app/views/certificados/show.html.erb
<p id="notice"><%= notice %></p>
<%= @certificado.nombre %>
<%= link_to 'Edit', edit_certificado_path(@certificado) %> |
<%= link_to 'Back', certificados_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsflisol</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>